galaxy_info:
  role_name: worker
  author: lazhar
  description: Ansible role for worker k0s
  license: MIT
  min_ansible_version: 2.4

  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all

  galaxy_tags:
    - debian
    - ubuntu

dependencies: []